# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Corgi < Formula
  desc "Command line interface for database configurations and other useful things, written in Go"
  homepage "https://github.com/Andriiklymiuk/corgi"
  version "1.20.37"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Andriiklymiuk/corgi/releases/download/v1.20.37/corgi_1.20.37_darwin_amd64.tar.gz"
      sha256 "d8039a86861862efc2bec5f944a8e92c32bbd8d2829efd1628b625c20c1413f0"

      define_method(:install) do
        bin.install "corgi"
        bash_completion.install "completions/corgi.bash" => "corgi"
        zsh_completion.install  "completions/corgi.zsh"  => "_corgi"
        fish_completion.install "completions/corgi.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Andriiklymiuk/corgi/releases/download/v1.20.37/corgi_1.20.37_darwin_arm64.tar.gz"
      sha256 "f5ed0ad42d218e311a3564394d6fed2ecf3693ffd52b34eac7c588ed086f5a7e"

      define_method(:install) do
        bin.install "corgi"
        bash_completion.install "completions/corgi.bash" => "corgi"
        zsh_completion.install  "completions/corgi.zsh"  => "_corgi"
        fish_completion.install "completions/corgi.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Andriiklymiuk/corgi/releases/download/v1.20.37/corgi_1.20.37_linux_amd64.tar.gz"
      sha256 "3245f46942c9994a4229ace260945e62cbc7e7240b76db0277f0c6a5f322d762"
      define_method(:install) do
        bin.install "corgi"
        bash_completion.install "completions/corgi.bash" => "corgi"
        zsh_completion.install  "completions/corgi.zsh"  => "_corgi"
        fish_completion.install "completions/corgi.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Andriiklymiuk/corgi/releases/download/v1.20.37/corgi_1.20.37_linux_arm64.tar.gz"
      sha256 "46a3ef9988256c411292a1bd7fd0d30161cdf96142d72aa402e0239121b93079"
      define_method(:install) do
        bin.install "corgi"
        bash_completion.install "completions/corgi.bash" => "corgi"
        zsh_completion.install  "completions/corgi.zsh"  => "_corgi"
        fish_completion.install "completions/corgi.fish"
      end
    end
  end

  def caveats
    <<~EOS
      Shell tab-completion installed for bash, zsh, fish:
        corgi run --services <TAB>      # services from corgi-compose.yml
        corgi run --dbServices <TAB>    # db_services
        corgi script -n <TAB>           # script names per service
        corgi tunnel <TAB>              # tunnelable services

      zsh users — if `<TAB>` shows files instead of names, your shell
      isn't loading brew's site-functions. Add this to ~/.zshrc BEFORE
      `compinit` (one-time, fixes all brew-installed completions):

        FPATH="#{HOMEBREW_PREFIX}/share/zsh/site-functions:$FPATH"
        autoload -Uz compinit && compinit

      Then: `rm -f ~/.zcompdump* && exec zsh`

      What's new:
        https://github.com/Andriiklymiuk/corgi/releases/tag/v#{version}
    EOS
  end
end
