# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Corgi < Formula
  desc "Command line interface for database configurations and other useful things, written in Go"
  homepage "https://github.com/Andriiklymiuk/corgi"
  version "1.16.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Andriiklymiuk/corgi/releases/download/v1.16.1/corgi_1.16.1_darwin_amd64.tar.gz"
      sha256 "ef094de66ce0cf45df1027ac84113358729810438c37c6a7b042729843881471"

      define_method(:install) do
        bin.install "corgi"
        bash_completion.install "completions/corgi.bash" => "corgi"
        zsh_completion.install  "completions/corgi.zsh"  => "_corgi"
        fish_completion.install "completions/corgi.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Andriiklymiuk/corgi/releases/download/v1.16.1/corgi_1.16.1_darwin_arm64.tar.gz"
      sha256 "d82e291ae4b63db8e99e37267d9a0c5476cdf17ef79adb11dd1342755f21b5d0"

      define_method(:install) do
        bin.install "corgi"
        bash_completion.install "completions/corgi.bash" => "corgi"
        zsh_completion.install  "completions/corgi.zsh"  => "_corgi"
        fish_completion.install "completions/corgi.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Andriiklymiuk/corgi/releases/download/v1.16.1/corgi_1.16.1_linux_amd64.tar.gz"
      sha256 "1e78cfce8d49db7b931b45ea2b93de082e24f86dffb802f14b522a0dddd313eb"
      define_method(:install) do
        bin.install "corgi"
        bash_completion.install "completions/corgi.bash" => "corgi"
        zsh_completion.install  "completions/corgi.zsh"  => "_corgi"
        fish_completion.install "completions/corgi.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Andriiklymiuk/corgi/releases/download/v1.16.1/corgi_1.16.1_linux_arm64.tar.gz"
      sha256 "678cf54ebd513c75dd1344598cf257e7648dfbd07dcfc432e2def00dd738c284"
      define_method(:install) do
        bin.install "corgi"
        bash_completion.install "completions/corgi.bash" => "corgi"
        zsh_completion.install  "completions/corgi.zsh"  => "_corgi"
        fish_completion.install "completions/corgi.fish"
      end
    end
  end

  def caveats
    <<~EOS
      Shell tab-completion installed for bash, zsh, fish.
        corgi run --services <TAB>      # services from corgi-compose.yml
        corgi run --dbServices <TAB>    # db_services
        corgi script -n <TAB>           # script names per service
        corgi tunnel <TAB>              # tunnel-able services
      zsh users may need to run `compinit` once or open a new shell.

      What's new in this release:
        https://github.com/Andriiklymiuk/corgi/releases/tag/v#{version}
    EOS
  end
end
