# This file was generated by GoReleaser. DO NOT EDIT.
cask "corgi" do
  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/corgi"], must_succeed: false
  end

  version "2.31.8"

  on_macos do
    on_arm do
      sha256 "d1813ea582d3e7f4a249c06547339357f9f2f5552f7de4229c67f302ad3dc597"
      url "https://github.com/Andriiklymiuk/corgi/releases/download/v#{version}/corgi_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "73129c025b83c00758f9caa49a4b7763a38935c9a4363dbd4df208ac57987cef"
      url "https://github.com/Andriiklymiuk/corgi/releases/download/v#{version}/corgi_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6dbb8356dad5ff862b1ff4f285e731900c2d334a1ba24f15fa3a65f894bf792c"
      url "https://github.com/Andriiklymiuk/corgi/releases/download/v#{version}/corgi_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "dab4d60354ec2419c9c8c1d7ad9b1b620aef3847c9251ed326be4519cefa47d7"
      url "https://github.com/Andriiklymiuk/corgi/releases/download/v#{version}/corgi_#{version}_linux_amd64.tar.gz"
    end
  end

  name "corgi"
  desc "Command line interface for database configurations and other useful things, written in Go"
  homepage "https://github.com/Andriiklymiuk/corgi"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "corgi"
  bash_completion "completions/corgi.bash"
  fish_completion "completions/corgi.fish"
  zsh_completion "completions/corgi.zsh"

  # No zap stanza required

  caveats <<~EOS
    What's new: https://github.com/Andriiklymiuk/corgi/releases/tag/v#{version}
    Tab completion installed for bash, zsh, fish - if <TAB> shows files: corgi completion zsh --help
  EOS
end
