# This file was generated by GoReleaser. DO NOT EDIT.
cask "corgi" do
  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/corgi"], must_succeed: false
  end

  version "2.28.10"

  on_macos do
    on_arm do
      sha256 "069d72bbc93e49ba35ae1b33ca530e29f457732c403adf651008e3882c9110c1"
      url "https://github.com/Andriiklymiuk/corgi/releases/download/v#{version}/corgi_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "07a72a4ca2e26ccd60ce3c897bcfff96274364f6e9e2794092f759624cfc17b3"
      url "https://github.com/Andriiklymiuk/corgi/releases/download/v#{version}/corgi_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "11fab05844b287f958f436eda52c26c8c1289bcb379203bde315744512e2ef79"
      url "https://github.com/Andriiklymiuk/corgi/releases/download/v#{version}/corgi_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "645a8eecfd5beca75b72970d43d6706828b4cdc41c86a6397919078905cde370"
      url "https://github.com/Andriiklymiuk/corgi/releases/download/v#{version}/corgi_#{version}_linux_amd64.tar.gz"
    end
  end

  name "corgi"
  desc "Command line interface for database configurations and other useful things, written in Go"
  homepage "https://github.com/Andriiklymiuk/corgi"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "corgi"
  bash_completion "completions/corgi.bash"
  fish_completion "completions/corgi.fish"
  zsh_completion "completions/corgi.zsh"

  # No zap stanza required

  caveats <<~EOS
    What's new: https://github.com/Andriiklymiuk/corgi/releases/tag/v#{version}
    Tab completion installed for bash, zsh, fish — if <TAB> shows files: corgi completion zsh --help
  EOS
end
