# This file was generated by GoReleaser. DO NOT EDIT.
cask "corgi" do
  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/corgi"], must_succeed: false
  end

  version "2.20.0"

  on_macos do
    on_arm do
      sha256 "b5f3cf28fdab8e3603faa0b095da4a16d9879ba5e93ad73ac5715f0799e1eaf8"
      url "https://github.com/Andriiklymiuk/corgi/releases/download/v#{version}/corgi_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0c7f9092798b7142b241cef944aa6f37280ae266c87653dcd48996651bc05139"
      url "https://github.com/Andriiklymiuk/corgi/releases/download/v#{version}/corgi_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ce55bf99306b027ed9952f5f81380f082d5abdefeb5f19101e846a0b75f0697f"
      url "https://github.com/Andriiklymiuk/corgi/releases/download/v#{version}/corgi_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c9f238539119cee4a101da5cea5b040a4d33db0a05047fc59cd9cc01694ca7ce"
      url "https://github.com/Andriiklymiuk/corgi/releases/download/v#{version}/corgi_#{version}_linux_amd64.tar.gz"
    end
  end

  name "corgi"
  desc "Command line interface for database configurations and other useful things, written in Go"
  homepage "https://github.com/Andriiklymiuk/corgi"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "corgi"
  bash_completion "completions/corgi.bash"
  fish_completion "completions/corgi.fish"
  zsh_completion "completions/corgi.zsh"

  # No zap stanza required

  caveats <<~EOS
    What's new: https://github.com/Andriiklymiuk/corgi/releases/tag/v#{version}
    Tab completion installed for bash, zsh, fish — if <TAB> shows files: corgi completion zsh --help
  EOS
end
